{{- if or (eq .Values.role "Aggregator") (eq .Values.role "Stateless-Aggregator") }}
apiVersion: v1
kind: Secret
metadata:
  name: vector-aggregator-custom
  namespace: {{ include "vector.namespaceOverride" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
    {{- include "vector.config.labels" . | nindent 4 }}
stringData:
  vector.yaml: |
    sources:
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
      http:
        type: http_server
        address: 0.0.0.0:6001
        strict_path: false
    transforms:
      vector_dispatcher:
        inputs:
        - vector
        route:
          auditing:
            source: ._type == "auditing"
            type: vrl
          events:
            source: ._type == "events"
            type: vrl
          logs:
            source: ._type == "logs"
            type: vrl
        type: route
      http_dispatcher:
        inputs:
        - http
        route:
          notification_history:
            source: .path == "/notification-history"
            type: vrl
          auditing:
            source: .path == "/auditing"
            type: vrl
        type: route
  {{ end }}