{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector.fullname" . }}
  namespace: {{ include "vector.namespaceOverride" . }}
  labels:
    {{- include "vector.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.ipFamilyPolicy }}
{{- end }}
{{- if .Values.service.ipFamilies }}
{{- with .Values.service.ipFamilies }}
  ipFamilies:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  ports:
{{- if or .Values.service.ports .Values.existingConfigMaps }}
  {{- toYaml .Values.service.ports | nindent 4 }}
{{- else if .Values.customConfig }}
  {{- include "vector.ports" . | indent 4 }}
{{- else if or (eq .Values.role "Aggregator") (eq .Values.role "Stateless-Aggregator") }}
    - name: api
      protocol: TCP
      port: 8686
      targetPort: 8686
    - name: vector
      protocol: TCP
      port: 6000
      targetPort: 6000
    - name: http
      protocol: TCP
      port: 6001
      targetPort: 6001
{{- else if (eq .Values.role "Agent") }}
    - name: prom-exporter
      port: 9090
      protocol: TCP
{{- end }}
  selector:
    {{- include "vector.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
  {{- with .Values.service.topologyKeys }}
  topologyKeys:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
